[[ISSUERS]]
address = "rBDtUygw2AZTiZoHiN1WeWK8e4R5vVFsva"
name = "Robotto"

[[TOKENS]]
issuer = "rBDtUygw2AZTiZoHiN1WeWK8e4R5vVFsva"
currency = "RBT"
name = "Robotto"
desc = "Robotto is a community driven memecoin built for fun, culture, and creativity on the XRP Ledger. Born from the vibrant Robotto NFT collection already live on xrp.cafe"
icon = "https://rbtxrpl.github.io/rbt-token/RBT-token.png"

[[TOKENS.URLS]]
url = "https://rbtxrpl.github.io/rbt-token/"
type = "website"
